import { MenuItem } from '@/types';

export const mockMenuItems: MenuItem[] = [
  // BIRYANIS - Main catering items
  {
    id: '1',
    name: 'Hyderabadi Mutton Biryani',
    description: 'Authentic Hyderabadi style mutton biryani with tender mutton pieces, aromatic basmati rice and traditional spices',
    price: 450,
    category_id: 'biryani',
    type_id: 'non-veg',
    image_url: 'https://images.pexels.com/photos/1624487/pexels-photo-1624487.jpeg?auto=compress&cs=tinysrgb&w=800',
    unit_type: 'kg',
    min_order_qty: 1,
    max_order_qty: 10,
    stock_quantity: 50,
    preparation_time: 60,
    pre_order_time: 4,
    is_available: true,
    is_featured: true,
    featured_priority: 1,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'Chicken Biryani',
    description: 'Fragrant basmati rice with tender chicken pieces, aromatic spices and saffron',
    price: 350,
    category_id: 'biryani',
    type_id: 'non-veg',
    image_url: 'https://images.pexels.com/photos/1624487/pexels-photo-1624487.jpeg?auto=compress&cs=tinysrgb&w=800',
    unit_type: 'kg',
    min_order_qty: 1,
    max_order_qty: 10,
    stock_quantity: 60,
    preparation_time: 50,
    pre_order_time: 3,
    is_available: true,
    is_featured: true,
    featured_priority: 2,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '3',
    name: 'Hyderabadi Chicken Biryani',
    description: 'Traditional Hyderabadi style chicken biryani with dum cooking method',
    price: 380,
    category_id: 'biryani',
    type_id: 'non-veg',
    image_url: 'https://images.pexels.com/photos/1624487/pexels-photo-1624487.jpeg?auto=compress&cs=tinysrgb&w=800',
    unit_type: 'kg',
    min_order_qty: 1,
    max_order_qty: 10,
    stock_quantity: 45,
    preparation_time: 55,
    pre_order_time: 4,
    is_available: true,
    is_featured: true,
    featured_priority: 3,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '4',
    name: 'Mutton Biryani',
    description: 'Rich and flavorful mutton biryani with tender mutton and aromatic rice',
    price: 420,
    category_id: 'biryani',
    type_id: 'non-veg',
    image_url: 'https://images.pexels.com/photos/1624487/pexels-photo-1624487.jpeg?auto=compress&cs=tinysrgb&w=800',
    unit_type: 'kg',
    min_order_qty: 1,
    max_order_qty: 10,
    stock_quantity: 40,
    preparation_time: 65,
    pre_order_time: 4,
    is_available: true,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '5',
    name: 'Veg Biryani',
    description: 'Aromatic basmati rice with mixed vegetables, nuts and traditional spices',
    price: 250,
    category_id: 'biryani',
    type_id: 'veg',
    image_url: 'https://images.pexels.com/photos/1624487/pexels-photo-1624487.jpeg?auto=compress&cs=tinysrgb&w=800',
    unit_type: 'kg',
    min_order_qty: 1,
    max_order_qty: 10,
    stock_quantity: 70,
    preparation_time: 40,
    pre_order_time: 2,
    is_available: true,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '6',
    name: 'Egg Biryani',
    description: 'Flavorful biryani with boiled eggs and fragrant basmati rice',
    price: 200,
    category_id: 'biryani',
    type_id: 'egg',
    image_url: 'https://images.pexels.com/photos/1624487/pexels-photo-1624487.jpeg?auto=compress&cs=tinysrgb&w=800',
    unit_type: 'kg',
    min_order_qty: 1,
    max_order_qty: 10,
    stock_quantity: 55,
    preparation_time: 45,
    pre_order_time: 2,
    is_available: true,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },

  // CURRIES & GRAVIES
  {
    id: '7',
    name: 'Mutton Curry',
    description: 'Rich and spicy mutton curry with traditional Indian spices',
    price: 400,
    category_id: 'curries',
    type_id: 'non-veg',
    image_url: 'https://images.pexels.com/photos/2338407/pexels-photo-2338407.jpeg?auto=compress&cs=tinysrgb&w=800',
    unit_type: 'kg',
    min_order_qty: 1,
    max_order_qty: 8,
    stock_quantity: 35,
    preparation_time: 50,
    pre_order_time: 3,
    is_available: true,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '8',
    name: 'Chicken Curry',
    description: 'Traditional home-style chicken curry with authentic spices',
    price: 320,
    category_id: 'curries',
    type_id: 'non-veg',
    image_url: 'https://images.pexels.com/photos/2338407/pexels-photo-2338407.jpeg?auto=compress&cs=tinysrgb&w=800',
    unit_type: 'kg',
    min_order_qty: 1,
    max_order_qty: 8,
    stock_quantity: 45,
    preparation_time: 40,
    pre_order_time: 2,
    is_available: true,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '9',
    name: 'Butter Chicken',
    description: 'Rich and creamy tomato-based chicken curry with butter and cream',
    price: 350,
    category_id: 'curries',
    type_id: 'non-veg',
    image_url: 'https://images.pexels.com/photos/2282532/pexels-photo-2282532.jpeg?auto=compress&cs=tinysrgb&w=800',
    unit_type: 'kg',
    min_order_qty: 1,
    max_order_qty: 8,
    stock_quantity: 40,
    preparation_time: 35,
    pre_order_time: 2,
    is_available: true,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '10',
    name: 'Kadai Chicken',
    description: 'Spicy chicken curry cooked with bell peppers, onions and kadai spices',
    price: 330,
    category_id: 'curries',
    type_id: 'non-veg',
    image_url: 'https://images.pexels.com/photos/8753659/pexels-photo-8753659.jpeg?auto=compress&cs=tinysrgb&w=800',
    unit_type: 'kg',
    min_order_qty: 1,
    max_order_qty: 8,
    stock_quantity: 30,
    preparation_time: 35,
    pre_order_time: 2,
    is_available: true,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '11',
    name: 'Paneer Butter Masala',
    description: 'Creamy tomato gravy with soft paneer cubes and Indian spices',
    price: 280,
    category_id: 'curries',
    type_id: 'veg',
    image_url: 'https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg?auto=compress&cs=tinysrgb&w=800',
    unit_type: 'kg',
    min_order_qty: 1,
    max_order_qty: 8,
    stock_quantity: 50,
    preparation_time: 25,
    pre_order_time: 1,
    is_available: true,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '12',
    name: 'Dal Makhani',
    description: 'Rich and creamy black lentils cooked with butter and cream',
    price: 200,
    category_id: 'curries',
    type_id: 'veg',
    image_url: 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg?auto=compress&cs=tinysrgb&w=800',
    unit_type: 'kg',
    min_order_qty: 1,
    max_order_qty: 10,
    stock_quantity: 60,
    preparation_time: 30,
    pre_order_time: 1,
    is_available: true,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '13',
    name: 'Chana Masala',
    description: 'Spicy chickpea curry with traditional Indian spices',
    price: 180,
    category_id: 'curries',
    type_id: 'veg',
    image_url: 'https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg?auto=compress&cs=tinysrgb&w=800',
    unit_type: 'kg',
    min_order_qty: 1,
    max_order_qty: 10,
    stock_quantity: 55,
    preparation_time: 25,
    pre_order_time: 1,
    is_available: true,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },

  // RICE VARIETIES
  {
    id: '14',
    name: 'Jeera Rice',
    description: 'Basmati rice tempered with cumin seeds and ghee',
    price: 120,
    category_id: 'rice',
    type_id: 'veg',
    image_url: 'https://images.pexels.com/photos/3926110/pexels-photo-3926110.jpeg?auto=compress&cs=tinysrgb&w=800',
    unit_type: 'kg',
    min_order_qty: 1,
    max_order_qty: 15,
    stock_quantity: 100,
    preparation_time: 15,
    is_available: true,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '15',
    name: 'Plain Rice',
    description: 'Steamed basmati rice - perfect with curries',
    price: 80,
    category_id: 'rice',
    type_id: 'veg',
    image_url: 'https://images.pexels.com/photos/3926110/pexels-photo-3926110.jpeg?auto=compress&cs=tinysrgb&w=800',
    unit_type: 'kg',
    min_order_qty: 1,
    max_order_qty: 20,
    stock_quantity: 150,
    preparation_time: 20,
    is_available: true,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '16',
    name: 'Pulao Rice',
    description: 'Fragrant basmati rice cooked with whole spices and ghee',
    price: 140,
    category_id: 'rice',
    type_id: 'veg',
    image_url: 'https://images.pexels.com/photos/3926110/pexels-photo-3926110.jpeg?auto=compress&cs=tinysrgb&w=800',
    unit_type: 'kg',
    min_order_qty: 1,
    max_order_qty: 15,
    stock_quantity: 80,
    preparation_time: 25,
    is_available: true,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },

  // BREADS
  {
    id: '17',
    name: 'Tandoori Roti',
    description: 'Whole wheat bread cooked in traditional tandoor',
    price: 15,
    category_id: 'breads',
    type_id: 'veg',
    image_url: 'https://images.pexels.com/photos/4449068/pexels-photo-4449068.jpeg?auto=compress&cs=tinysrgb&w=800',
    unit_type: 'piece',
    min_order_qty: 10,
    max_order_qty: 100,
    stock_quantity: 500,
    preparation_time: 5,
    is_available: true,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '18',
    name: 'Butter Naan',
    description: 'Soft leavened bread with butter - perfect for curries',
    price: 25,
    category_id: 'breads',
    type_id: 'veg',
    image_url: 'https://images.pexels.com/photos/4449068/pexels-photo-4449068.jpeg?auto=compress&cs=tinysrgb&w=800',
    unit_type: 'piece',
    min_order_qty: 5,
    max_order_qty: 50,
    stock_quantity: 300,
    preparation_time: 8,
    is_available: true,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '19',
    name: 'Garlic Naan',
    description: 'Naan topped with garlic and butter',
    price: 30,
    category_id: 'breads',
    type_id: 'veg',
    image_url: 'https://images.pexels.com/photos/7625056/pexels-photo-7625056.jpeg?auto=compress&cs=tinysrgb&w=800',
    unit_type: 'piece',
    min_order_qty: 5,
    max_order_qty: 50,
    stock_quantity: 250,
    preparation_time: 8,
    is_available: true,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '20',
    name: 'Kulcha',
    description: 'Soft leavened bread perfect for pairing with curries',
    price: 20,
    category_id: 'breads',
    type_id: 'veg',
    image_url: 'https://images.pexels.com/photos/4449068/pexels-photo-4449068.jpeg?auto=compress&cs=tinysrgb&w=800',
    unit_type: 'piece',
    min_order_qty: 5,
    max_order_qty: 50,
    stock_quantity: 200,
    preparation_time: 6,
    is_available: true,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },

  // STARTERS
  {
    id: '21',
    name: 'Tandoori Chicken',
    description: 'Marinated chicken grilled in traditional tandoor with aromatic spices',
    price: 380,
    category_id: 'starters',
    type_id: 'non-veg',
    image_url: 'https://images.pexels.com/photos/3850838/pexels-photo-3850838.jpeg?auto=compress&cs=tinysrgb&w=800',
    unit_type: 'kg',
    min_order_qty: 1,
    max_order_qty: 5,
    stock_quantity: 30,
    preparation_time: 30,
    is_available: true,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '22',
    name: 'Chicken 65',
    description: 'Spicy deep-fried chicken with South Indian spices',
    price: 320,
    category_id: 'starters',
    type_id: 'non-veg',
    image_url: 'https://images.pexels.com/photos/15876621/pexels-photo-15876621.jpeg?auto=compress&cs=tinysrgb&w=800',
    unit_type: 'kg',
    min_order_qty: 1,
    max_order_qty: 5,
    stock_quantity: 25,
    preparation_time: 20,
    is_available: true,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '23',
    name: 'Paneer Tikka',
    description: 'Marinated paneer cubes grilled with bell peppers and onions',
    price: 280,
    category_id: 'starters',
    type_id: 'veg',
    image_url: 'https://images.pexels.com/photos/14477865/pexels-photo-14477865.jpeg?auto=compress&cs=tinysrgb&w=800',
    unit_type: 'kg',
    min_order_qty: 1,
    max_order_qty: 5,
    stock_quantity: 35,
    preparation_time: 20,
    is_available: true,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '24',
    name: 'Fish Fry',
    description: 'Crispy fried fish marinated with coastal spices',
    price: 350,
    category_id: 'starters',
    type_id: 'non-veg',
    image_url: 'https://images.pexels.com/photos/262959/pexels-photo-262959.jpeg?auto=compress&cs=tinysrgb&w=800',
    unit_type: 'kg',
    min_order_qty: 1,
    max_order_qty: 3,
    stock_quantity: 20,
    preparation_time: 25,
    is_available: true,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },

  // DESSERTS
  {
    id: '25',
    name: 'Gulab Jamun',
    description: 'Soft milk solid balls soaked in sugar syrup',
    price: 8,
    category_id: 'desserts',
    type_id: 'veg',
    image_url: 'https://images.pexels.com/photos/4449068/pexels-photo-4449068.jpeg?auto=compress&cs=tinysrgb&w=800',
    unit_type: 'piece',
    min_order_qty: 10,
    max_order_qty: 100,
    stock_quantity: 500,
    preparation_time: 5,
    is_available: true,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '26',
    name: 'Rasmalai',
    description: 'Soft paneer patties in sweetened milk',
    price: 12,
    category_id: 'desserts',
    type_id: 'veg',
    image_url: 'https://images.pexels.com/photos/4449068/pexels-photo-4449068.jpeg?auto=compress&cs=tinysrgb&w=800',
    unit_type: 'piece',
    min_order_qty: 10,
    max_order_qty: 80,
    stock_quantity: 300,
    preparation_time: 5,
    is_available: true,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '27',
    name: 'Kheer',
    description: 'Traditional rice pudding with nuts and cardamom',
    price: 150,
    category_id: 'desserts',
    type_id: 'veg',
    image_url: 'https://images.pexels.com/photos/4449068/pexels-photo-4449068.jpeg?auto=compress&cs=tinysrgb&w=800',
    unit_type: 'kg',
    min_order_qty: 1,
    max_order_qty: 10,
    stock_quantity: 40,
    preparation_time: 30,
    is_available: true,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },

  // BEVERAGES
  {
    id: '28',
    name: 'Mango Lassi',
    description: 'Creamy yogurt drink with fresh mango pulp',
    price: 80,
    category_id: 'beverages',
    type_id: 'veg',
    image_url: 'https://images.pexels.com/photos/1410236/pexels-photo-1410236.jpeg?auto=compress&cs=tinysrgb&w=800',
    unit_type: 'liter',
    min_order_qty: 1,
    max_order_qty: 10,
    stock_quantity: 100,
    preparation_time: 5,
    is_available: true,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '29',
    name: 'Masala Chai',
    description: 'Traditional Indian spiced tea',
    price: 40,
    category_id: 'beverages',
    type_id: 'veg',
    image_url: 'https://images.pexels.com/photos/1793035/pexels-photo-1793035.jpeg?auto=compress&cs=tinysrgb&w=800',
    unit_type: 'liter',
    min_order_qty: 1,
    max_order_qty: 20,
    stock_quantity: 200,
    preparation_time: 5,
    is_available: true,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '30',
    name: 'Fresh Lime Soda',
    description: 'Refreshing lime juice with soda',
    price: 60,
    category_id: 'beverages',
    type_id: 'veg',
    image_url: 'https://images.pexels.com/photos/96974/pexels-photo-96974.jpeg?auto=compress&cs=tinysrgb&w=800',
    unit_type: 'liter',
    min_order_qty: 1,
    max_order_qty: 15,
    stock_quantity: 150,
    preparation_time: 5,
    is_available: true,
    is_featured: false,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
];

export const categoryNames: Record<string, string> = {
  'biryani': 'Biryani',
  'curries': 'Curries & Gravies',
  'rice': 'Rice Varieties',
  'breads': 'Breads',
  'starters': 'Starters',
  'desserts': 'Desserts',
  'beverages': 'Beverages',
};

export const typeNames: Record<string, { name: string; color: string }> = {
  'veg': { name: 'Veg', color: '#22C55E' },
  'non-veg': { name: 'Non-Veg', color: '#EF4444' },
  'egg': { name: 'Egg', color: '#F59E0B' },
  'vegan': { name: 'Vegan', color: '#10B981' },
};